name: Sword-Proto
version: 0.0.0
homepage: https://github.com/sshine/sword-proto
extra-source-files:
  - README.md

dependencies:
  - base
  - containers
  - data-dword
  - text
  - megaparsec
  - parser-combinators
  - prettyprinter

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TypeApplications

library:
  exposed-modules:
    - Sword.Contract
    - Sword.Contract.Parser
    - Sword.Contract.Pretty
    - Sword.Time
  source-dirs: src

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - Sword-Proto
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec
