name: Sword-Proto
version: 0.0.0
homepage: https://github.com/sshine/sword-proto
extra-source-files:
  - README.md

dependencies:
  - base
  - containers
  - data-dword
  - data-fix
# - data-fix-cse
  - text
  - thyme
  - megaparsec
  - parser-combinators

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

library:
  exposed-modules:
    - Sword.Contract
    - Sword.Contract.Parser
    - Sword.Time
  source-dirs: src

tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
      - jq
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-hedgehog
      - hedgehog
      - hspec
